version: '3.9'

services:
  init:
    image: nvidia/cuda:11.7.1-runtime-ubuntu20.04
    container_name: u3ml_init

    volumes:
      - type: bind
        source: ../
        target: /work/

    command: ['/bin/bash', './init/init.sh']
    working_dir: /work
    network_mode: bridge
