version: '3.9'

services:
  init:
    image: python:3.12.0
    container_name: uthreeml-init

    volumes:
      - type: bind
        source: ../
        target: /work/

    command: ['/bin/bash', './init/init.sh']
    working_dir: /work
    network_mode: bridge
