version: '3.9'

services:
  init:
    image: python:3.10.6@sha256:745efdfb7e4aac9a8422bd8c62d8bc35a693e8979a240d29677cb03e6aa91052
    container_name: uthreeml-init

    volumes:
      - type: bind
        source: ../
        target: /work/

    command: ['/bin/bash', './init/init.sh']
    working_dir: /work
    network_mode: bridge
