version: '3.9'

services:
  init:
    image: python:3.11.2@sha256:0d753a7365274cef746b34dde9b4aaa27644f64e1567ed8f40ccd191ac4bd530
    container_name: uthreeml-init

    volumes:
      - type: bind
        source: ../
        target: /work/

    command: ['/bin/bash', './init/init.sh']
    working_dir: /work
    network_mode: bridge
