name: Build Container Image
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'Pipfile'
      - 'Pipfile.lock'
      - '.github/workflows/pr-check.yml'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.0.2
      - run: |
          docker build .

