name: PR Check
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'Pipfile'
      - 'Pipfile.lock'
      - 'init.sh'
      - 'launch.sh'
      - '.python-version'
      - '.github/workflows/pr-check.yml'

jobs:
  build_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0

      - uses: docker/setup-buildx-action@v2.2.1

      - name: Build
        uses: docker/build-push-action@v3.1.1
        with:
          context: .
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
